# Generated by Django 3.2.3 on 2021-06-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_productname', models.CharField(max_length=100)),
                ('chosen_price', models.IntegerField()),
            ],
        ),
    ]
