# Generated by Django 3.2.3 on 2021-06-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chart',
            new_name='Cart',
        ),
    ]
