# Generated by Django 3.2.3 on 2021-06-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quentity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='username',
        ),
    ]
